// AUTO-GENERATED by packages/contracts/scripts/export-abis.js — do not edit manually

export const SANOVA_ASSET_TOKEN_ABI = [
  'event Approval(address indexed owner, address indexed spender, uint256 value)',
  'event KycUpdated(address indexed account, bool approved)',
  'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
  'event Transfer(address indexed from, address indexed to, uint256 value)',
  'function kycApproved(address ) view',
  'function setKyc(address account, bool approved)',
] as const;
