const fs = require('node:fs');
const path = require('node:path');

const contractsRoot = path.resolve(__dirname, '..');
const monorepoRoot = path.resolve(contractsRoot, '../..');
const apiBlockchainDir = path.join(monorepoRoot, 'apps/api/src/blockchain');
const sharedAbiDir = path.join(contractsRoot, 'abi');

function loadArtifact(contractFile) {
  const contractName = path.basename(contractFile, '.sol');
  const artifactPath = path.join(
    contractsRoot,
    'artifacts/contracts',
    contractFile,
    `${contractName}.json`
  );

  return JSON.parse(fs.readFileSync(artifactPath, 'utf8')).abi;
}

function formatEvent(item) {
  const args = (item.inputs ?? [])
    .map((input) => `${input.type}${input.indexed ? ' indexed' : ''} ${input.name}`)
    .join(', ');

  return `event ${item.name}(${args})`;
}

function formatFunction(item) {
  const args = (item.inputs ?? []).map((input) => `${input.type} ${input.name}`).join(', ');
  const outputs = (item.outputs ?? [])
    .filter((output) => output.name)
    .map((output) => `${output.type} ${output.name}`)
    .join(', ');
  const mutability = item.stateMutability ?? 'nonpayable';
  const returnsClause = outputs.length ? ` returns (${outputs})` : '';

  return `function ${item.name}(${args})${returnsClause}${mutability === 'view' ? ' view' : ''}`;
}

function buildHumanReadableAbi(abi, options = {}) {
  const includeFunctions = new Set(options.includeFunctions ?? []);
  const fragments = [];

  for (const item of abi) {
    if (item.type === 'event' && item.name) {
      fragments.push(formatEvent(item));
      continue;
    }

    if (item.type === 'function' && item.name && includeFunctions.has(item.name)) {
      fragments.push(formatFunction(item));
    }
  }

  return fragments;
}

function writeAbiModule(targetPath, exportName, fragments) {
  const contents = `// AUTO-GENERATED by packages/contracts/scripts/export-abis.js — do not edit manually

export const ${exportName} = [
${fragments.map((fragment) => `  '${fragment}',`).join('\n')}
] as const;
`;

  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, contents, 'utf8');
}

function main() {
  const escrowAbi = loadArtifact('EscrowLendingPool.sol');
  const assetAbi = loadArtifact('SanovaAssetToken.sol');

  const escrowFragments = buildHumanReadableAbi(escrowAbi, {
    includeFunctions: ['distributeYieldAndAmortize', 'liquidityAsset']
  });

  const assetFragments = buildHumanReadableAbi(assetAbi, {
    includeFunctions: ['setKyc', 'kycApproved']
  });

  writeAbiModule(path.join(apiBlockchainDir, 'escrow-lending-pool.abi.ts'), 'ESCROW_LENDING_POOL_ABI', escrowFragments);
  writeAbiModule(path.join(apiBlockchainDir, 'sanova-asset-token.abi.ts'), 'SANOVA_ASSET_TOKEN_ABI', assetFragments);

  writeAbiModule(path.join(sharedAbiDir, 'escrow-lending-pool.abi.ts'), 'ESCROW_LENDING_POOL_ABI', escrowFragments);
  writeAbiModule(path.join(sharedAbiDir, 'sanova-asset-token.abi.ts'), 'SANOVA_ASSET_TOKEN_ABI', assetFragments);

  const erc3643Shim = `// AUTO-GENERATED by packages/contracts/scripts/export-abis.js — do not edit manually
export { SANOVA_ASSET_TOKEN_ABI as ERC3643_ASSET_ABI } from './sanova-asset-token.abi';
`;

  fs.writeFileSync(path.join(apiBlockchainDir, 'erc3643-asset.abi.ts'), erc3643Shim, 'utf8');
  fs.writeFileSync(path.join(sharedAbiDir, 'erc3643-asset.abi.ts'), erc3643Shim, 'utf8');

  const frontendAbiPath = path.join(monorepoRoot, 'apps/web/src/contracts/abis.ts');
  const frontendContents = `// AUTO-GENERATED by packages/contracts/scripts/export-abis.js — do not edit manually

/** On-chain dividend event emitted by EscrowLendingPool.distributeYieldAndAmortize */
export const ESCROW_DIVIDEND_EVENT_NAME = 'YieldDistributedAndAmortized' as const;

/** KYC status updates on SanovaAssetToken */
export const ASSET_KYC_EVENT_NAME = 'KycUpdated' as const;

export const ASSET_TRANSFER_EVENT_NAME = 'Transfer' as const;
`;

  fs.mkdirSync(path.dirname(frontendAbiPath), { recursive: true });
  fs.writeFileSync(frontendAbiPath, frontendContents, 'utf8');

  console.log('[export-abis] Wrote API, shared, and frontend ABI modules from compiled artifacts.');
}

main();
