-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "preferredTheme" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pwaInstalledAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pwaDismissedAt" TIMESTAMP(3);
