import type { Metadata } from 'next';
import {
  intlLocaleByCode,
  messagesByLocale,
  rtlLocales,
  type Locale
} from '../../i18n';
import { withLocalePrefix } from '../i18n/localeRouting';
import { locales } from '../../i18n';
import { getSiteUrl } from './siteUrl';

// fix: 6 remove sw_KE (Swahili/Kenya — not a supported locale); add mr_IN (Marathi/India)
const OG_LOCALE_MAP: Partial<Record<Locale, string>> = {
  en: 'en_US',
  es: 'es_AR',
  pt: 'pt_BR',
  fr: 'fr_FR',
  de: 'de_DE',
  zh: 'zh_CN',
  hi: 'hi_IN',
  ar: 'ar_SA',
  bn: 'bn_BD',
  ru: 'ru_RU',
  ur: 'ur_PK',
  id: 'id_ID',
  ja: 'ja_JP',
  mr: 'mr_IN',
  he: 'he_IL'
};

export function buildSiteMetadata(locale: Locale, path = '/'): Metadata {
  const messages = messagesByLocale[locale];
  const siteUrl = getSiteUrl();
  const canonicalPath = path === '/' ? '' : path;
  // Self-referencing canonical: each locale must point to its own prefixed
  // URL (e.g. /en/faq), never to the Spanish version — otherwise hreflang
  // and canonical contradict each other and Google drops the translation.
  const canonical = `${siteUrl}${withLocalePrefix(locale, canonicalPath || '/')}`;

  // Dynamic OG image generated by /opengraph-image.tsx (1200×630)
  // Falls back to static path for pages that have a custom OG image
  const ogImage = `${siteUrl}/opengraph-image`;

  const keywords = messages.meta.keywords ?? '';
  const openGraphLocale = OG_LOCALE_MAP[locale] ?? 'en_US';
  const alternateLocales = Object.entries(OG_LOCALE_MAP)
    .filter(([code]) => code !== locale)
    .map(([, og]) => og);

  return {
    metadataBase: new URL(siteUrl),
    applicationName: 'Sanova',
    manifest: '/manifest.json',
    appleWebApp: {
      capable: true,
      statusBarStyle: 'black-translucent',
      title: 'Sanova'
    },
    // fix: 7 template appends "| Sanova Global" — child pages must NOT include it in their title string
    title: {
      default: messages.meta.title,
      template: `%s | Sanova Global`
    },
    description: messages.meta.description,
    keywords: keywords.split(',').map((k) => k.trim()).filter(Boolean),
    authors: [{ name: 'Sanova Global SAS', url: siteUrl }],
    creator: 'Sanova Global',
    publisher: 'Sanova Global SAS',
    category: 'finance',
    alternates: {
      canonical,
      languages: {
        ...Object.fromEntries(
          locales.map((code) => [code, `${siteUrl}${withLocalePrefix(code, canonicalPath || '/')}`])
        ),
        'x-default': `${siteUrl}${canonicalPath || '/'}`
      }
    },
    openGraph: {
      type: 'website',
      locale: openGraphLocale,
      alternateLocale: alternateLocales,
      url: canonical,
      siteName: 'Sanova Global',
      title: messages.meta.title,
      description: messages.meta.description,
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: messages.meta.ogImageAlt ?? 'Sanova Global — Tokenized Real Estate in Vaca Muerta, Argentina',
          type: 'image/png'
        }
      ]
    },
    twitter: {
      card: 'summary_large_image',
      site: '@SanovaGlobal',
      creator: '@SanovaGlobal',
      title: messages.meta.title,
      description: messages.meta.description,
      images: [ogImage]
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        'max-image-preview': 'large',
        'max-snippet': -1,
        'max-video-preview': -1
      }
    },
    // Verification tokens — replace with real tokens from Search Console / Yandex Webmaster
    verification: {
      google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION ?? undefined,
      yandex: process.env.NEXT_PUBLIC_YANDEX_SITE_VERIFICATION ?? undefined
    },
    other: {
      'geo.region': 'AR-N',
      'geo.placename': 'Vaca Muerta, Neuquén, Argentina',
      'geo.position': '-38.5;-69.0',
      'ICBM': '-38.5, -69.0'
    }
  };
}

export function htmlDirForLocale(locale: Locale): 'ltr' | 'rtl' {
  return rtlLocales.includes(locale) ? 'rtl' : 'ltr';
}

export function htmlLangForLocale(locale: Locale): string {
  return intlLocaleByCode[locale] ?? locale;
}
