// AUTO-GENERATED by packages/contracts/scripts/export-abis.js — do not edit manually

/** On-chain dividend event emitted by EscrowLendingPool.distributeYieldAndAmortize */
export const ESCROW_DIVIDEND_EVENT_NAME = 'YieldDistributedAndAmortized' as const;

/** KYC status updates on SanovaAssetToken */
export const ASSET_KYC_EVENT_NAME = 'KycUpdated' as const;

export const ASSET_TRANSFER_EVENT_NAME = 'Transfer' as const;
